name: Vistopia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4  # En güncel sürüm
  permission_handler: ^10.4.3
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  intl: ^0.18.1  # Tarih ve zaman işlemleri için
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "image/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "image/1.1.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - image/
    - image/imagemainpersonel/
    - fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans_Condensed-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
